import asyncio
import httpx
import time

async def main():
    async with httpx.AsyncClient(base_url="http://localhost:8000", timeout=30.0) as client:
        # 1. Register a new office without type and without office_slug under DM Office
        # DM Office ID is e301b235-3308-4369-adc8-495c45324ec3
        parent_id = "e301b235-3308-4369-adc8-495c45324ec3"
        ts = int(time.time())
        
        reg_payload = {
            "parent_id": parent_id,
            "name": f"Land Records Office Test {ts}",
            "official_email": f"lro_test_{ts}@gov.in",
            "official_phone": "0381-2228888",
            "address_line_1": "Revenue Building, Agartala",
            "district": "West Tripura",
            "state": "Tripura",
            "pincode": "799002",
            "admin_name": "Prasenjit Debbarma Test",
            "admin_designation": "Sub-Registrar",
            "admin_email": f"prasenjit.lro_test_{ts}@gov.in",
            "admin_mobile": "9876543211",
            "admin_password": "nicadmin2026",
        }
        
        # POST /registrations/offices
        print("Step 1: Submitting registration request...")
        res = await client.post("/registrations/offices", json=reg_payload)
        print("Response Status:", res.status_code)
        assert res.status_code == 200, f"Registration failed: {res.text}"
        reg_data = res.json()
        req_id = reg_data["id"]
        office_id = reg_data["office_id"]
        print("Registration submitted successfully! Request ID:", req_id, "Office ID:", office_id)
        print("Autogenerated Office Code:", reg_data["office"]["code"])
        print("Default Office Type:", reg_data["office"]["type"])
        
        # 2. Login as the DM Administrator
        print("\nStep 2: Logging in as DM Administrator...")
        login_payload = {
            "email": "dm@gov.in",
            "password": "dmadmin2026"
        }
        res_login = await client.post("/auth/login", json=login_payload)
        print("Login Response Status:", res_login.status_code)
        assert res_login.status_code == 200, f"Login failed: {res_login.text}"
        token_data = res_login.json()
        token = token_data["access_token"]
        print("Logged in successfully! Token received.")
        
        headers = {"Authorization": f"Bearer {token}"}
        
        # 3. Get pending registrations
        print("\nStep 3: Fetching pending registrations as DM Admin...")
        res_pending = await client.get("/registrations/pending", headers=headers)
        print("Pending Status:", res_pending.status_code)
        assert res_pending.status_code == 200, f"Failed to get pending: {res_pending.text}"
        pending_list = res_pending.json()
        print(f"Found {len(pending_list)} pending registration request(s) in queue:")
        for r in pending_list:
            print(f"  - Request ID: {r['id']}, Office: {r['office']['name']}, Parent: {r['parent_office_id']}")
        
        # Find our request
        matching_req = [r for r in pending_list if r["id"] == req_id]
        assert len(matching_req) > 0, "Registered request was not found in the DM's pending queue!"
        print("Successfully verified: our request is visible in DM's queue!")
        
        # 4. Approve the registration request
        print("\nStep 4: Approving the registration request as DM Admin...")
        approve_payload = {"review_note": f"Approved by DM via automation {ts}"}
        res_approve = await client.post(f"/registrations/{req_id}/approve", json=approve_payload, headers=headers)
        print("Approve Response Status:", res_approve.status_code)
        assert res_approve.status_code == 200, f"Approval failed: {res_approve.text}"
        approve_data = res_approve.json()
        print("Approval response status field:", approve_data["status"])
        print("Approved office status field:", approve_data["office"]["approval_status"])
        print("Approved user status field:", approve_data["primary_user"]["status"])
        
        # 5. Check if the newly approved office is returned in get_all_offices
        print("\nStep 5: Verifying office presence in DM's hierarchy...")
        res_offices = await client.get("/registrations/offices/all", headers=headers)
        assert res_offices.status_code == 200
        offices_list = res_offices.json()
        matching_office = [o for o in offices_list if o["id"] == office_id]
        assert len(matching_office) > 0, "Approved office is not present in DM's hierarchy list!"
        print("Successfully verified: newly approved office is now present in DM's hierarchy tree!")
        
        print("\nAll steps completed successfully!")

if __name__ == "__main__":
    asyncio.run(main())
