from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select, and_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.auth.dependencies import get_current_user
from app.core.database import get_session
from app.core.audit import log_audit_event
from app.models import User, Office, OfficeAncestor, Meeting, MeetingGuest
from app.meetings.schemas import (
    MeetingCreate,
    MeetingOut,
    MeetingUpdate,
    MeetingPostpone,
    MeetingGuestCreate,
    MeetingGuestOut,
)

router = APIRouter()


async def get_visible_office_ids(session: AsyncSession, user: User) -> list[UUID]:
    if user.role == "SUPER_ADMIN":
        # Super admin can see all offices
        stmt = select(Office.id)
        res = await session.execute(stmt)
        return res.scalars().all()

    if not user.office_id:
        return []

    # Get all descendant offices of the user's office
    stmt = select(OfficeAncestor.descendant_office_id).where(
        OfficeAncestor.ancestor_office_id == user.office_id
    )
    res = await session.execute(stmt)
    return res.scalars().all()


async def check_meeting_write_permission(
    session: AsyncSession, user: User, meeting: Meeting
) -> None:
    if user.role == "SUPER_ADMIN":
        return
    if not user.office_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You must be associated with an office to modify meetings.",
        )
    # Check if the meeting belongs to the user's office or its descendants
    visible_ids = await get_visible_office_ids(session, user)
    if meeting.office_id not in visible_ids:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to manage this meeting.",
        )


@router.post("/", response_model=MeetingOut, status_code=status.HTTP_201_CREATED)
async def create_meeting(
    payload: MeetingCreate,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    if not current_user.office_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User must be associated with an office to create a meeting.",
        )

    meeting = Meeting(
        office_id=current_user.office_id,
        title=payload.title,
        agenda=payload.agenda,
        time=payload.time,
        date=payload.date,
        venue=payload.venue,
        institution_name=payload.institution_name,
        department_name=payload.department_name,
        meeting_type=payload.meeting_type,
        chairperson=payload.chairperson,
        status="upcoming",
    )
    session.add(meeting)
    await session.flush()

    await log_audit_event(session, current_user.id, "MEETING_CREATED", "meeting", meeting.id)
    await session.commit()

    # Reload meeting to populate office relation and autogenerated fields post-commit
    stmt = (
        select(Meeting)
        .where(Meeting.id == meeting.id)
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
    )
    meeting = (await session.execute(stmt)).scalar_one()

    meeting_out = MeetingOut.model_validate(meeting)
    meeting_out.office_name = meeting.office.name
    return meeting_out


@router.get("/", response_model=list[MeetingOut])
async def list_meetings(
    current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)
):
    visible_office_ids = await get_visible_office_ids(session, current_user)
    if not visible_office_ids:
        return []

    stmt = (
        select(Meeting)
        .where(Meeting.office_id.in_(visible_office_ids))
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
        .order_by(Meeting.date.desc(), Meeting.time.desc())
    )

    res = await session.execute(stmt)
    meetings = res.scalars().all()

    meetings_out = []
    for m in meetings:
        mout = MeetingOut.model_validate(m)
        mout.office_name = m.office.name
        meetings_out.append(mout)

    return meetings_out


@router.get("/{meeting_id}", response_model=MeetingOut)
async def get_meeting(
    meeting_id: UUID,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    stmt = (
        select(Meeting)
        .where(Meeting.id == meeting_id)
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
    )
    res = await session.execute(stmt)
    meeting = res.scalar_one_or_none()

    if not meeting:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Meeting not found.")

    await check_meeting_write_permission(session, current_user, meeting)

    meeting_out = MeetingOut.model_validate(meeting)
    meeting_out.office_name = meeting.office.name
    return meeting_out


@router.put("/{meeting_id}", response_model=MeetingOut)
async def update_meeting(
    meeting_id: UUID,
    payload: MeetingUpdate,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    stmt = (
        select(Meeting)
        .where(Meeting.id == meeting_id)
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
    )
    res = await session.execute(stmt)
    meeting = res.scalar_one_or_none()

    if not meeting:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Meeting not found.")

    await check_meeting_write_permission(session, current_user, meeting)

    # Update fields
    for field, val in payload.model_dump(exclude_unset=True).items():
        setattr(meeting, field, val)

    await log_audit_event(session, current_user.id, "MEETING_UPDATED", "meeting", meeting.id)
    await session.commit()

    # Reload meeting to populate office relation and autogenerated fields post-commit
    stmt = (
        select(Meeting)
        .where(Meeting.id == meeting.id)
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
    )
    meeting = (await session.execute(stmt)).scalar_one()

    meeting_out = MeetingOut.model_validate(meeting)
    meeting_out.office_name = meeting.office.name
    return meeting_out


@router.patch("/{meeting_id}/postpone", response_model=MeetingOut)
async def postpone_meeting(
    meeting_id: UUID,
    payload: MeetingPostpone,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    stmt = (
        select(Meeting)
        .where(Meeting.id == meeting_id)
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
    )
    res = await session.execute(stmt)
    meeting = res.scalar_one_or_none()

    if not meeting:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Meeting not found.")

    await check_meeting_write_permission(session, current_user, meeting)

    meeting.date = payload.date
    meeting.time = payload.time
    meeting.status = "upcoming"

    await log_audit_event(session, current_user.id, "MEETING_POSTPONED", "meeting", meeting.id)
    await session.commit()

    # Reload meeting to populate office relation and autogenerated fields post-commit
    stmt = (
        select(Meeting)
        .where(Meeting.id == meeting.id)
        .options(selectinload(Meeting.office), selectinload(Meeting.guests))
    )
    meeting = (await session.execute(stmt)).scalar_one()

    meeting_out = MeetingOut.model_validate(meeting)
    meeting_out.office_name = meeting.office.name
    return meeting_out


@router.delete("/{meeting_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_meeting(
    meeting_id: UUID,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    stmt = select(Meeting).where(Meeting.id == meeting_id)
    res = await session.execute(stmt)
    meeting = res.scalar_one_or_none()

    if not meeting:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Meeting not found.")

    await check_meeting_write_permission(session, current_user, meeting)

    await session.delete(meeting)
    await log_audit_event(session, current_user.id, "MEETING_DELETED", "meeting", meeting_id)
    await session.commit()


@router.post(
    "/{meeting_id}/guests", response_model=MeetingGuestOut, status_code=status.HTTP_201_CREATED
)
async def add_meeting_guest(
    meeting_id: UUID,
    payload: MeetingGuestCreate,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    stmt = select(Meeting).where(Meeting.id == meeting_id)
    res = await session.execute(stmt)
    meeting = res.scalar_one_or_none()

    if not meeting:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Meeting not found.")

    await check_meeting_write_permission(session, current_user, meeting)

    guest = MeetingGuest(
        meeting_id=meeting.id,
        name=payload.name,
        phone=payload.phone,
        email=payload.email,
        office=payload.office,
        department=payload.department,
        designation=payload.designation,
    )
    session.add(guest)
    await session.flush()

    await log_audit_event(
        session, current_user.id, "MEETING_GUEST_ADDED", "meeting_guest", guest.id
    )
    await session.commit()

    # Reload guest to populate autogenerated fields post-commit
    stmt = select(MeetingGuest).where(MeetingGuest.id == guest.id)
    guest = (await session.execute(stmt)).scalar_one()

    return MeetingGuestOut.model_validate(guest)


@router.delete("/{meeting_id}/guests/{guest_id}", status_code=status.HTTP_204_NO_CONTENT)
async def remove_meeting_guest(
    meeting_id: UUID,
    guest_id: UUID,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    stmt = select(Meeting).where(Meeting.id == meeting_id)
    res = await session.execute(stmt)
    meeting = res.scalar_one_or_none()

    if not meeting:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Meeting not found.")

    await check_meeting_write_permission(session, current_user, meeting)

    guest_stmt = select(MeetingGuest).where(
        and_(MeetingGuest.id == guest_id, MeetingGuest.meeting_id == meeting_id)
    )
    guest = (await session.execute(guest_stmt)).scalar_one_or_none()

    if not guest:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Guest not found in this meeting."
        )

    await session.delete(guest)
    await log_audit_event(
        session, current_user.id, "MEETING_GUEST_REMOVED", "meeting_guest", guest_id
    )
    await session.commit()
